services:
  backend:
    env_file: 
      - .env
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/backend              # Maps the entire backend directory on your host machine to the /backend directory in the container
      - ./backend/data:/backend/data:rw # Mounts SQLite database with read/write permissions
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_APP=api.py
      - BACKEND_GOOGLE_MAPS_API_KEY=${BACKEND_GOOGLE_MAPS_API_KEY}
      - BACKEND_METEOMATICS_USERNAME=${BACKEND_METEOMATICS_USERNAME}
      - BACKEND_METEOMATICS_PASSWORD=${BACKEND_METEOMATICS_PASSWORD}
      
  frontend:
    env_file: 
      - .env
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production
      - REACT_APP_MAPTILER_KEY=${REACT_APP_MAPTILER_KEY}
      - REACT_APP_MAPTILER_API_KEY=${REACT_APP_MAPTILER_API_KEY}
      - REACT_APP_USER_ID=${REACT_APP_USER_ID}
      - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
