services:
  backend:
    env_file: 
      - .env
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_DEBUG=0
      - FLASK_APP=src/app.py
      - FLASK_ENV=production
      - BACKEND_GOOGLE_MAPS_API_KEY=${BACKEND_GOOGLE_MAPS_API_KEY}
      - BACKEND_METEOMATICS_USERNAME=${BACKEND_METEOMATICS_USERNAME}
      - BACKEND_METEOMATICS_PASSWORD=${BACKEND_METEOMATICS_PASSWORD}
      - BACKEND_METEOSOURCE_API_KEY=${BACKEND_METEOSOURCE_API_KEY}      
      # Github Variables for Backend Page
      - BACKEND_GITHUB_ACCESS_TOKEN=${BACKEND_GITHUB_ACCESS_TOKEN}
      - BACKEND_GITHUB_OWNER=${BACKEND_GITHUB_OWNER}
      - BACKEND_GITHUB_REPO=${BACKEND_GITHUB_REPO}

  frontend:
    env_file: 
      - .env
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_MAPTILER_KEY=${REACT_APP_MAPTILER_KEY}
      - REACT_APP_MAPTILER_API_KEY=${REACT_APP_MAPTILER_API_KEY}
      - REACT_APP_USER_ID=${REACT_APP_USER_ID}
      - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
      - REACT_APP_METEOSOURCE_API_KEY=${REACT_APP_METEOSOURCE_API_KEY}
