services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" # Port Flask is served on
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Port React is served on
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file change detection in Docker
