services:
  backend:
    build: ./backend
    ports:
      - "80:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_APP=app.py
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production
