name: Deploy to AWS EC2

on:
  push:
    branches: ['main']

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          debug: true
          script: |
            # Stop and remove all running containers
            docker stop $(docker ps -a -q) || true
            docker rm $(docker ps -a -q) || true

            # Remove all images except the latest one
            docker image prune -af

            cd ~/production/Airstorm-GFS
            git pull
            docker-compose up -d --build
